config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  get 'students/index'

  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.role == ('admin' || 'cashier' || 'developer') if request.env['warden'].user }, as: :admin_root

  resources :students do
  	get :autocomplete_student_full_name, on: :collection
    resources :payments, only: [:new, :create, :edit, :update], module: :students
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/payments" => "students#payments", as: :payments, via: [:get], on: :member
    match "/options" => "students#options", as: :options, via: [:get], on: :member
    match "/enroll" => "students#enroll", as: :enroll, via: [:get, :post]
    match "/report" => "students#report", via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :settings
  resources :courses
  resources :fees

end

app/views/layouts/shared/_sidebar_for_cashier.html.erb
<ul class="nav navbar-nav">
  <li>
    <a href="">
      <span class="title">MAIN NAVIGATION</span>
    </a>
  </li>
  <li>
    <a href="/students/index">
      <span class="icon fa fa-shopping-basket"></span><span class="title">Students</span>
    </a>
  </li>
  <li>
    <%= link_to settings_path do %>
      <span class="icon fa fa-gear"></span><span class="title">Settings</span>
    <% end %>
  </li>
</ul>

app/views/layouts/shared/_sidebar_for_owner.html.erb
<ul class="nav navbar-nav">
  <li>
    <a href="">
      <span class="title">MAIN NAVIGATION</span>
    </a>
  </li>
  <!-- <li>
    <a href="/account/index">
      <span class="icon fa fa-home"></span><span class="title">Account</span>
    </a>
  </li> -->
  <li>
    <a href="/students/index">
      <span class="icon fa fa-shopping-basket"></span><span class="title">Students</span>
    </a>
  </li>
</ul>