config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  get 'students/index'

  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.role == ('admin' || 'cashier' || 'developer') if request.env['warden'].user }, as: :admin_root

  resources :students do
  	get :autocomplete_student_full_name, on: :collection
    resources :payments, only: [:new, :create, :edit, :update], module: :students
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/payments" => "students#payments", as: :payments, via: [:get], on: :member
    match "/options" => "students#options", as: :options, via: [:get], on: :member
    match "/enroll" => "students#enroll", as: :enroll, via: [:get, :post]
    match "/report" => "students#report", via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :settings
  resources :courses
  resources :fees

end

app/models/student.rb
class Student < ApplicationRecord

	include PgSearch
  include Filterable
  pg_search_scope :search_by_name, :against => [:full_name, :lr_number]
  scope :by_course, -> (course_id) { where course_id: course_id }
  scope :by_track, -> (track_id) { where track_id: track_id }
  scope :by_year_level, -> (year_level_id) { where year_level_id: year_level_id }
  
	belongs_to :course
	belongs_to :track
	belongs_to :year_level
	has_one :address, dependent: :destroy
  has_many :subscriptions
  has_many :payments
	has_attached_file :profile_photo,
                    styles: { large: "120x120>",
                   medium: "70x70>",
                    thumb: "40x40>",
                    small: "30x30>",
                    x_small: "20x20>"},
                      default_url: ":style/profile_default.jpg",
                    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                    :url => "/system/:attachment/:id/:style/:filename"
  validates_attachment :profile_photo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	enum gender: [:male, :female]

  accepts_nested_attributes_for :address

	validates :lr_number, :first_name, :last_name, :middle_name, :gender, :course_id, presence: true
  validates :lr_number, uniqueness: true
  
  before_save :set_full_name, :set_track

  delegate :details, to: :address, prefix: true, allow_nil: true
  
  def fullname
    "#{first_name} #{middle_name.first.capitalize}. #{last_name}"
  end

  def reversed_name
  	"#{last_name}, #{first_name} #{middle_name.first.capitalize}."
  end

  def strand
    if course.track.abbr.blank?
      "#{course}"
    else
      "#{course.track.abbr} - #{course}"
    end
  end

  def tuition_fee
    Fee.where(:miscelaneous => false).sum(:amount)
  end

  def miscelaneous_fee
    Fee.where(:miscelaneous => true).sum(:amount)
  end

  def total_fee
    tuition_fee + (miscelaneous_fee * 2)
  end

  def current_subscription
    subscriptions.last
  end

  def previous_subscription
    subscription.first
  end

  def current_subscription_amount
    if subscriptions.present?
      subscriptions.last.amount
    else
      0
    end
  end

  def current_subscription_payment_total
    if current_subscription.present?
      current_subscription.payments.sum(:amount)
    else
      0
    end
  end

  def current_balance
    current_subscription_amount - current_subscription_payment_total
  end

  def subscription_paid?
    current_balance == 0
  end

  def status
    if subscription_paid?
      "Paid"
    end
  end

  def last_payment_created_at
    current_subscription.payments.last.created_at
  end

  def set_year_level!
    grade_11 = YearLevel.find_by(name: "Grade 11")
    grade_12 = YearLevel.find_by(name: "Grade 12")
    if subscriptions.count == 1
      self.update(year_level_id: grade_11.id)
    else
      self.update(year_level_id: grade_12.id)
    end
  end

  def subscribe!
    Subscription.create!(name: "SY #{Time.now.year}-#{Time.now.next_year.year}",
      amount: total_fee, student_id: self.id)
    set_year_level!
  end

  private
  def set_full_name
    self.full_name = fullname
  end

  def set_track
    course = Course.find(course_id)
    self.track_id = course.track.id
  end
end

app/controllers/students/payments_controller.rb
module Students
  class PaymentsController < ApplicationController

    def new
      @student = Student.find(params[:student_id])
      @payment = @student.payments.build
    end

    def create
      @student = Student.find(params[:student_id])
      @payment = @student.payments.create(payment_params)
    end

    def edit
      @student = Student.find(params[:student_id])
      @payment = Payment.find(params[:id])
    end

    def update
      @student = Student.find(params[:student_id])
      @payment.update(track_params)
    end

    def destroy
      @payment = Track.find(params[:id])
      @payment.destroy
      redirect_to settings_url, notice: 'Track deleted!'
    end

    private
    def payment_params
      params.require(:payment).permit(:amount, :subscription_id, :student_id)
    end

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	autocomplete :student, :full_name, full: true

	def autocomplete
    @students = Student.all
    @names = @students.map { |m| m.full_name }
    render json: @names
  end

	def index
		@tracks = Track.all
		@courses = Course.all
		@year_levels = YearLevel.all
		@track = params[:track_id] if params[:track_id].present?
		@course = params[:course_id] if params[:course_id].present?
		@year_level = params[:year_level_id] if params[:year_level_id].present?
		@balance_status = params[:balance_status]
		@full_name = params[:full_name]

		if @full_name.present?
      @filtered = Student.order(:last_name).search_by_name(params[:full_name])
      @students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
    else
    	respond_to do |format|
    		format.html do
    			if @balance_status.present?
    				if @balance_status == "w/ balance"
				    	@filtered = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level).select{|s| s.subscription_paid? == false}
				    	@students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
				    else
				    	@filtered = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level).select{|s| s.subscription_paid? == true}
				    	@students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
				    end
			    else
			    	@filtered = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level)
				    @students = Kaminari.paginate_array(@filtered).page(params[:page]).per(30)
			    	#@students = Student.where(nil)
			    	#filtering_params(params).each do |value|
			    	#	@students = @students.public_send(value) if value.present?
			    	#end
			    end
		    end
		  end
    end
	end

	def report
		@track = params[:track_id] if params[:track_id].present?
		@course = params[:course_id] if params[:course_id].present?
		@year_level = params[:year_level_id] if params[:year_level_id].present?
		@balance_status = params[:balance_status]
		if @balance_status.present?
			if @balance_status == "w/ balance"
	    	@students = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level).select{|s| s.subscription_paid? == false}
	    else
	    	@students = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level).select{|s| s.subscription_paid? == true}
	    end
    else
    	@students = Student.filter(by_track: @track, by_course: @course, by_year_level: @year_level)
    end
    respond_to do |format|
  		format.html
			format.pdf do
				pdf = FilteredStudentsPdf.new(@students, @track, @course, @year_level, @balance_status, view_context)
    		send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Students.pdf"
	    end
	  end
	end

	def new
		@student = Student.new
		@student.build_address
	end

	def create
		@fees = Fee.all
		if @fees.present?
			@student = Student.create(student_params)
    	if @student.save
				@student.subscribe!
				redirect_to payments_student_path(@student), notice: 'Student record has been saved.'
			else
				render :new
			end
		else
			render :new, notice: 'School Fees are not yet set.'
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		@student.update_attributes(student_params)
		if @student.save
			redirect_to info_student_path(@student), notice: 'Student record has been updated!'
		else
			render :edit
		end
	end

	def info
		@student = Student.find(params[:id])
	end

	def payments
		@student = Student.find(params[:id])
		@payments = @student.current_subscription.payments
	end

	def options
		@student = Student.find(params[:id])
	end

	def enroll
		@student = Student.find(params[:student_id])
		@student.subscribe!
		redirect_to payments_student_path(@student), notice: 'Enrollment done.'
	end

	def destroy
		@student = Student.find(params[:id])
	end

	private
  def student_params
    params.require(:student).permit(
    	:last_name, 
    	:first_name, 
    	:middle_name, 
    	:gender, 
    	:profile_photo, 
    	:course_id,
    	:track_id,
    	:year_level_id,
    	:lr_number,
    	address_attributes:[:id, :house_number, :street, :barangay, :municipality, :province, :id ])
  end

  def filtering_params(params)
	  params.slice(:track_id, :course_id, :year_level_id, :balance_status)
	end
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <h4>
            <% if @student.new_record? %>
              New Student
            <% else %>
              Update Record
            <% end %>
          </h4>
        </div>
      </div>
    <div class="card-body">
      <%=simple_form_for @student do |f| %>
      <%= f.error_notification %>
        <div class="row">
          <div class="col-md-4">
            <%if @student.profile_photo.blank? %>
              <center><%=image_tag("default.png", height: 100, width: 100, :class=>"img-square -img-rounded") %></center>
            <% else %>
              <center><%= image_tag @student.profile_photo.url(:large), class: 'center-block img-responsive img-rounded'%></center>
            <% end %>
          <center><%= f.input :profile_photo, as: :file %></center>
          </div>
          <div class="col-md-3">
            <%=f.input :first_name, label: 'First Name' %>
            <%=f.input :middle_name, label: 'Middle Name' %>
            <%=f.input :last_name, label: 'Last Name' %>
            <%=f.input :gender, collection: Student.genders.keys.to_a.map {|s| [s.titleize, s]}, as: :radio_buttons, item_label_class: "radio-inline", item_wrapper_tag: false %>
          </div>
          <div class="col-md-5">
            <%=f.input :lr_number, label: 'LRN', input_html: {type: 'number'} %>
            <%=f.input :course_id, collection: Track.order(:name).all, as: :grouped_select, group_method: :courses %>
            <% unless @student.new_record? %>
              <%=f.input :year_level_id, label: 'Grade',collection: YearLevel.all, as: :radio_buttons %>
            <% end %>
          </div>
        </div>
	      <div class="modal-footer">
	        <%#= link_to 'Cancel', monitoring_project_path(@project), class: 'btn btn-default pull-left' %>
          <% if @student.new_record? %>
            <%= link_to "Cancel", students_path, class: "btn btn-default pull-left" %>
          <% else %>
            <%= link_to "Cancel", info_student_path(@student), class: "btn btn-default pull-left" %>
          <% end %>
	        <%=f.submit "Save", class: "btn btn-primary" %>
	      </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $("#student_course_id").select2({
      theme: "bootstrap",
      width: '100%'
    });
  });
</script>

app/views/students/_show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card overlap-height">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-4">
              <div class="row">
                <div class="col-md-3">
                  <%if @student.profile_photo.blank? %>
                    <center><%=image_tag("default.png", height: 100, width: 100, :class=>"img-square -img-rounded") %></center>
                  <% else %>
                    <center><%= image_tag @student.profile_photo.url(:large), class: 'center-block img-responsive img-rounded'%></center>
                  <% end %>
                </div>
                <div class="col-md-9">
                  <h5><%=@student.fullname.try(:upcase) %></h5>
                  <p class="zero-margin">LRN: <%= @student.lr_number %></p>
                  <p class="zero-margin">Course: <%= @student.strand %></p>
                  <p class="zero-margin">Grade: <%= @student.year_level %></p>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <h4 class="text-success text-center"><%=number_to_currency @student.current_subscription_payment_total %></h4>
              <h5 style="margin-bottom: 1px" class="text-muted text-center">PAYMENTS</h5>
              <% if @student.current_subscription.payments.present? %>
                <small class="text-muted"><center>Updated <%= time_ago_in_words(@student.last_payment_created_at) %> ago</center></small>
              <% end %>
            </div>
            <div class="col-md-3">
              <h4 class="text-warning text-center"><%=number_to_currency @student.current_balance %></h4>
              <h5 style="margin-bottom: 1px" class="text-muted text-center">BALANCE</h5>
              <% if @student.subscription_paid? %>
                <small class="text-danger"><center>Paid</center></small>
              <% end %>
            </div>
            <div class="col-md-2">
              <% if @student.subscription_paid? %>
                <%= link_to "Enroll", student_enroll_path(@student), class: 'btn btn-lg btn-success pull-right' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
      <div class="nav-tabs-navigation">
        <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
          <li class="<%='active' if current_page? info_student_path %>">
            <%= link_to 'Info', info_student_path %>
          </li>
          <li class="<%='active' if current_page? payments_student_path %>">
            <%= link_to 'Payments', payments_student_path %>
          </li>
          <li class="pull-right <%='active' if current_page? options_student_path %>">
              <%= link_to 'Options', options_student_path %>
            </li>
        </ul>
      </div>
      <div class="content">
        <div id="my-tab-content" class="tab-content">
          <%= render '/students/partials/info' if current_page? info_student_path %>
          <%= render '/students/partials/payments' if current_page? payments_student_path %>
          <%= render '/students/partials/options' if current_page? options_student_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        	<div class="row">
	          <div class="col-md-3">
	            <h4 class="title"> Students </h4>
	          </div>
	          <div class="col-md-6">
	            <%=form_tag students_path, method: :get do %>
	              <div class="input-group stylish-input-group" id="product-prefetch">
	                <%= autocomplete_field_tag "full_name", params[:full_name], autocomplete_student_full_name_students_path, class: 'form-control', placeholder: 'Search Student' %>
	                <span class="input-group-btn">
	                  <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
	                    <i class="fa fa-search"></i>
	                  <% end %>
	                </span>
	              </div>
	            <% end %>
	          </div>
          	<div class="col-md-3">
	            <span class="pull-right">
	              <%= link_to "New Student", new_student_path, class: "btn btn-primary" %>
	            </span>
	          </div>
	        </div>
          <hr>
          <div class="row">
            <div class="col-md-12">
              <h4>Filter Options:</h4>
              <%= form_tag students_path, method: :get do%>
                <div class="row">
                  <div class="col-md-3">
                    <%= select_tag :track_id, options_from_collection_for_select(@tracks, "id", "name", params[:track_id]), :class => 'form-control border-input', :prompt => "-- Select Course Classification --" %>
                  </div>
                  <div class="col-md-3">
                    <%= select_tag :course_id, options_from_collection_for_select(@courses, "id", "name", params[:course_id]), :class => 'form-control border-input', :prompt => "-- Select Course --" %>
                  </div>
                  <div class="col-md-3">
                    <%= select_tag :year_level_id, options_from_collection_for_select(@year_levels, "id", "name", params[:year_level_id]), :class => 'form-control border-input', :prompt => "-- Select Grade --" %>
                  </div>
                  <div class="col-md-3">
                    <%= select_tag :balance_status, options_for_select([ "w/ balance", "w/o balance" ], params[:balance_status]), prompt: "-- Select Balance Status --", :class => 'form-control border-input' %>
                  </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-md-12">
                    <%=link_to "Print (PDF)", report_students_path(format: 'pdf', track_id: @track, course_id: @course, year_level_id: @year_level, balance_status: @balance_status), class: "btn btn-info active" if @students.present? %>
                    <div class=" pull-right">
                      <%= link_to "Reset Filter", students_path, class: 'btn btn-warning' %>
                      <button type="submit" class="btn btn-primary">Filter</button>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <p><%= "#{@filtered.count} result/s found." %></p>
        </div>
      </div>
      <div class="card-body">
      	<table class="table table-hover">
      		<tr>
            <th>LRN</th>
      			<th>Name</th>
      			<th>Course</th>
      			<th>Grade</th>
      			<th class="text-right">Balance</th>
      			<th></th>
      		</tr>
      		<% @students.each do |student| %>
      			<tr>
              <td><%= student.lr_number %></td>
      				<td><%= link_to student.reversed_name.upcase, info_student_path(student) %></td>
      				<td><%= student.strand %></td>
      				<td><%= student.year_level %></td>
      				<td class="text-right"><%= number_to_currency (student.current_balance) %></td>
      				<td></td>
      			</tr>
      		<% end %>
      	</table>
      	<div class="modal-footer">
          <center><%= paginate @students, :window => 1 %></center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/info.html.erb
<%= render 'show', locals: @student %>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/options.html.erb
<%= render 'show', locals: @student %>

app/views/students/payments.html.erb
<%= render 'show', locals: @student %>