config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  get 'students/index'

  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'students#index', :constraints => lambda { |request| request.env['warden'].user.role == ('admin' || 'cashier' || 'developer') if request.env['warden'].user }, as: :admin_root

  resources :students do
  	get :autocomplete_student_full_name, on: :collection
    resources :payments, only: [:new, :create, :edit, :update], module: :students
    match "/info" => "students#info", as: :info, via: [:get], on: :member
    match "/payments" => "students#payments", as: :payments, via: [:get], on: :member
    match "/options" => "students#options", as: :options, via: [:get], on: :member
    match "/enroll" => "students#enroll", as: :enroll, via: [:get, :post]
    match "/report" => "students#report", via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :settings
  resources :courses
  resources :fees

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

	def index
		@tracks = Track.order(:name).all
		@tuition_fees = Fee.tuition.order(:name).all
		@miscellaneous_fees = Fee.misc.order(:name).all
	end
end

app/views/settings/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-6">
              <h4>Courses</h4>
            </div>
            <div class="col-md-6">
              <span class="pull-right">
                <%= link_to "New Course", new_course_path, class: "btn btn-primary", remote: true %>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <% if Course.present? %>
            <% @tracks.all.each do |track| %>
              <tr>
                <th><%= track.name.upcase %></th>
              	<td class="text-right"></td>
              </tr>
              <% track.courses.order(:name).all.each do |course| %>
              	<tr>
            			<td>&nbsp - <%= course.name.upcase %></td>
  	            	<td class="text-right">
  	              	<%= link_to "Edit", edit_course_path(course), class: "btn btn-xs btn-warning", remote: true%>
                    <%= link_to course_path(course), method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <span class="text-danger" title="Delete Course" data-toggle='tooltip'><i class="fa fa-trash"></i></span>
                  <% end %>
  	              </td>
  	            </tr>
  	          <% end %>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-6">
              <h4>School Fees</h4>
            </div>
            <div class="col-md-6">
              <span class="pull-right">
                <%= link_to "New Fee", new_fee_path, class: "btn btn-primary", remote: true %>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h4>TUITION <span class="text-muted">(SCHOOL YEAR)</span></h4>
        <table class="table table-striped">
          <% @tuition_fees.all.each do |fee| %>
            <tr>
              <td><%= fee.name.titleize %></td>
              <td class="text-right"><%= number_to_currency fee.amount %></td>
              <td class="text-right">
                <%= link_to "Edit", edit_fee_path(fee), class: "btn btn-xs btn-warning", remote: true %>
                <%= link_to fee_path(fee), method: :delete, data: {confirm: 'Are you sure?'} do %>
                  <span class="text-danger" title="Delete Fee" data-toggle='tooltip'><i class="fa fa-trash"></i></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
        <h4>MISCELLANEOUS <span class="text-muted">(1 SEMESTER)</span></h4>
        <table class="table table-striped">
          <% @miscellaneous_fees.all.each do |fee| %>
            <tr>
              <td><%= fee.name.titleize %></td>
              <td class="text-right"><%= number_to_currency fee.amount %></td>
              <td class="text-right">
                <%= link_to "Edit", edit_fee_path(fee), class: "btn btn-xs btn-warning", remote: true %>
                <%= link_to fee_path(fee), method: :delete, data: {confirm: 'Are you sure?'} do %>
                  <span class="text-danger" title="Delete Fee" data-toggle='tooltip'><i class="fa fa-trash"></i></span>
                <% end %>
              </td>
            </tr>
          <% end %>
          <tr>
            <th class="text-right">Total Miscellaneous:</th>
            <th class="text-right"><%= number_to_currency @miscellaneous_fees.pluck(:amount).sum %></th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>